/* ═══════════════════════════════════════════════════════════════════════════
 * apps/console/app.js — app logic: routing, views, and the DUAL-MODE data layer
 * ───────────────────────────────────────────────────────────────────────────
 * 🇪🇸 ES — QUÉ HACE: toda la lógica del console. Enruta por hash, pinta las
 *     vistas y —lo importante— decide DE DÓNDE salen los datos en cada momento:
 *       1) MODO ONLINE   → la API responde: datos vivos.
 *       2) MODO CACHED   → el service worker (o Cache Storage / localStorage)
 *                          sirve la última respuesta buena: datos reales,
 *                          marcados con su hora.
 *       3) MODO SNAPSHOT → snapshot.json (generado por scripts/export-console-
 *                          snapshot.js): la app abre con contenido aunque NUNCA
 *                          haya habido servidor.
 *     La interfaz siempre dice en qué modo está. Un dato viejo nunca se disfraza
 *     de nuevo: esa es la regla de oro del modo offline.
 *     También registra el service worker, captura el prompt de instalación PWA
 *     y monta la navegación móvil (cajón + barra inferior + hoja "More").
 *
 * 🇬 EN — WHAT IT DOES: all the console logic. Routes by hash, renders views
 *     and —the important part— decides WHERE data comes from at every moment:
 *       1) ONLINE MODE   → the API answers: live data.
 *       2) CACHED MODE   → the service worker (or Cache Storage / localStorage)
 *                          serves the last good response: real data, stamped with
 *                          its time.
 *       3) SNAPSHOT MODE → snapshot.json (generated by
 *                          scripts/export-console-snapshot.js): the app opens
 *                          with content even if there was NEVER a server.
 *     The interface always says which mode it is in. Stale data is never
 *     disguised as fresh: that is the golden rule of offline mode.
 *     It also registers the service worker, captures the PWA install prompt and
 *     mounts the mobile navigation (drawer + bottom bar + "More" sheet).
 *
 * 🇧🇷 PT — O QUE FAZ: toda a lógica do console. Roteia por hash, renderiza as
 *     vistas e decide DE ONDE vêm os dados: ONLINE (API ao vivo), CACHED (service
 *     worker / Cache Storage / localStorage com a última resposta boa) ou SNAPSHOT
 *     (snapshot.json, para abrir sem nunca ter havido servidor). A interface
 *     sempre diz em qual modo está. Também registra o service worker, captura o
 *     prompt de instalação PWA e monta a navegação mobile.
 *
 * 🎓 BEGINNER COURSE / CURSO PARA PRINCIPIANTES / CURSO PARA INICIANTES
 *   • Tres capas de datos ES/EN/PT: red → caché → archivo estático. Cada capa es
 *     más lenta de actualizar pero más disponible. Probarlas EN ORDEN y caer a la
 *     siguiente es el patrón "graceful degradation": la app nunca muere, solo
 *     muestra datos menos frescos y lo avisa.
 *     Network → cache → static file: fall through in order, always flag freshness.
 *   • Cache Storage desde la página ES/EN/PT: `caches.match(url)` funciona también
 *     FUERA del service worker. Por eso, aunque el SW no llegue a registrarse
 *     (iframe raro, permiso denegado), la página puede leer lo que el SW guardó.
 *     Cache Storage is readable from page context too, not only from the worker.
 *   • localStorage y sus trampas ES/EN/PT: es síncrono, limitado (~5 MB) y lanza
 *     excepción si se llena. Por eso TODO acceso va en try/catch y solo guardamos
 *     respuestas pequeñas. Sync, ~5MB, throws when full: always try/catch.
 *   • `beforeinstallprompt` ES/EN/PT: el navegador OFRECE el evento cuando la app
 *     cumple los criterios de instalación (manifiesto, iconos, service worker,
 *     HTTPS). Hay que guardarlo y usarlo cuando el usuario pulse "Instalar"; si
 *     no se guarda, el prompt se pierde y no hay segunda oportunidad en esa visita.
 *     Capture the event on arrival; it does not come back.
 *   • Router por hash ES/EN/PT: `#/graph` no viaja al servidor (todo lo que sigue
 *     a # es del cliente), así que funciona offline y sin reglas de reescritura.
 *     Hash routing needs no server rules and works offline.
 *   • Hiperscript `el()` seguro ES/EN/PT: construimos nodos con `textContent`,
 *     nunca `innerHTML` con datos: el navegador no puede ejecutar HTML que llega
 *     como texto. DOM nodes + textContent is XSS-immune by design.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* ── Utilidades DOM / DOM helpers ─────────────────────────────────────────── */

function el(tag, props = {}, children = []) {
  const node = document.createElement(tag);
  for (const [key, value] of Object.entries(props)) {
    if (value === null || value === undefined || value === false) continue;
    if (key === 'class') node.className = value;
    else if (key === 'text') node.textContent = String(value);
    else if (key === 'dataset') Object.assign(node.dataset, value);
    else if (key.startsWith('on') && typeof value === 'function') node.addEventListener(key.slice(2).toLowerCase(), value);
    else node.setAttribute(key, String(value));
  }
  for (const child of [].concat(children)) {
    if (child === null || child === undefined || child === false) continue;
    node.appendChild(typeof child === 'string' || typeof child === 'number' ? document.createTextNode(String(child)) : child);
  }
  return node;
}

const badge = (text, color = '') => el('span', { class: `badge ${color ? `badge-${color}` : ''}`, text: String(text ?? '—') });
const statusColor = (status) => ({
  completed: 'green', approved: 'green', resolved: 'green', passed: 'green',
  blocked: 'red', failed: 'red', critical: 'red',
  running: 'blue', in_progress: 'blue', planned: 'yellow', stub: 'yellow', proposed: 'yellow', open: 'yellow',
}[status] ?? '');
const num = (value) => (value === null || value === undefined ? '—' : Number(value).toLocaleString('en-US'));
const truncate = (text, max = 180) => (String(text ?? '').length > max ? `${String(text).slice(0, max)}…` : String(text ?? ''));
const timeAgo = (iso) => {
  if (!iso) return 'never';
  const seconds = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 3600) return `${Math.round(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.round(seconds / 3600)}h ago`;
  return `${Math.round(seconds / 86400)}d ago`;
};

function highlight(snippet) {
  const text = String(snippet ?? '').replace(/\[\[/g, '\u0001').replace(/\]\]/g, '\u0002');
  const node = document.createElement('span');
  for (const part of text.split('\u0001')) {
    const [plain, marked] = part.split('\u0002');
    if (plain) node.appendChild(document.createTextNode(plain));
    if (marked) node.appendChild(el('span', { class: 'mark', text: marked }));
  }
  return node;
}

/* ── Capa de datos de DOS modos + snapshot / Dual-mode + snapshot data layer ─ */

const STORAGE_PREFIX = 'genesis:last:';
const connectionPill = () => document.getElementById('connection');
const modeBanner = () => document.getElementById('mode-banner');

const dataMode = { source: 'connecting', at: null, detail: '' };
let snapshotCache = null;
let installPromptEvent = null;
let swRegistration = null;

const MODE_COPY = {
  live: { pill: 'live', cls: 'pill-online', label: 'ONLINE · live data from the API' },
  cached: { pill: 'offline · cached', cls: 'pill-cached', label: 'OFFLINE · last known data (from cache)' },
  snapshot: { pill: 'snapshot', cls: 'pill-cached', label: 'SNAPSHOT · bundled data (no server reached yet)' },
  error: { pill: 'no data', cls: 'pill-offline', label: 'NO DATA · no server, no cache, no snapshot' },
  connecting: { pill: 'connecting…', cls: 'pill-offline', label: 'connecting…' },
};

function setMode(source, detail = '') {
  if (source === 'live' && dataMode.source === 'live' && !detail) return;
  dataMode.source = source;
  dataMode.detail = detail;
  if (source === 'live' || source === 'cached') dataMode.at = new Date().toISOString();

  const copy = MODE_COPY[source] ?? MODE_COPY.error;
  const pill = connectionPill();
  if (pill) {
    pill.textContent = copy.pill;
    pill.className = `pill ${copy.cls}`;
    pill.title = `${copy.label}${dataMode.at ? ` · synced ${timeAgo(dataMode.at)}` : ''}${detail ? ` · ${detail}` : ''}`;
  }

  const banner = modeBanner();
  if (banner) {
    if (source === 'live') {
      banner.hidden = true;
    } else {
      banner.hidden = false;
      banner.dataset.mode = source;
      banner.textContent = '';
      banner.appendChild(el('span', { text: copy.label }));
      if (dataMode.at) banner.appendChild(el('span', { class: 'mono', text: `synced ${timeAgo(dataMode.at)}` }));
      if (source === 'snapshot') banner.appendChild(el('span', { class: 'mono', text: 'run `genesis serve` for live data' }));
      const retry = el('button', { text: 'Retry now', onclick: () => refreshData() });
      banner.appendChild(retry);
    }
  }
  document.body.dataset.mode = source;
}

const snapshotKeyFor = (path) => path.replace(/^\/api\//, '');

function storeLocal(path, payload) {
  try {
    const text = JSON.stringify(payload);
    if (text.length > 400_000) return; // ES: no reventar la cuota | EN: do not blow the quota
    localStorage.setItem(STORAGE_PREFIX + path, JSON.stringify({ at: new Date().toISOString(), payload }));
  } catch { /* ES: cuota llena o modo privado: se ignora | EN: full quota or private mode: ignore */ }
}

function readLocal(path) {
  try {
    const raw = localStorage.getItem(STORAGE_PREFIX + path);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return parsed?.payload ? { at: parsed.at, payload: parsed.payload } : null;
  } catch { return null; }
}

async function readCacheStorage(path) {
  try {
    if (!('caches' in globalThis)) return null;
    const match = await caches.match(new URL(path, location.origin).href) ?? await caches.match(path);
    if (!match || !match.ok) return null;
    const type = match.headers.get('content-type') ?? '';
    return type.includes('json') ? await match.json() : await match.text();
  } catch { return null; }
}

async function readSnapshot(path) {
  if (snapshotCache === null) {
    try {
      const response = await fetch('./snapshot.json', { cache: 'no-store' });
      snapshotCache = response.ok ? await response.json() : false;
    } catch { snapshotCache = false; }
  }
  if (!snapshotCache) return null;
  const key = snapshotKeyFor(path);
  return snapshotCache.data?.[key] ?? null;
}

/**
 * ES: puerta única de datos. Orden: red → caché del SW → localStorage → snapshot.
 * EN: the single data door. Order: network → SW cache → localStorage → snapshot.
 * PT: porta única de dados. Ordem: rede → cache do SW → localStorage → snapshot.
 *
 * @param {string} path ruta de la API, p.ej. '/api/stats'
 * @param {object} [options] opciones de fetch (solo escrituras)
 */
async function api(path, options = {}) {
  try {
    const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options });
    const servedFromCache = response.headers.get('X-Genesis-Offline') === 'cached';
    if (!response.ok) {
      const detail = await response.json().catch(() => ({}));
      const error = new Error(detail?.error?.message ?? `HTTP ${response.status} on ${path}`);
      error.status = response.status;
      throw error;
    }
    const type = response.headers.get('content-type') ?? '';
    const payload = type.includes('application/json') ? await response.json() : await response.text();
    if (!options.method || options.method === 'GET') storeLocal(path, payload);
    setMode(servedFromCache ? 'cached' : 'live');
    return payload;
  } catch (error) {
    if (error.status && error.status < 500 && options.method && options.method !== 'GET') throw error;

    const fromCache = await readCacheStorage(path);
    if (fromCache !== null) { setMode('cached', `cache storage for ${path}`); return fromCache; }

    const fromLocal = readLocal(path);
    if (fromLocal) { dataMode.at = fromLocal.at; setMode('cached', `local copy for ${path}`); return fromLocal.payload; }

    const fromSnapshot = await readSnapshot(path);
    if (fromSnapshot !== null) { setMode('snapshot'); return fromSnapshot; }

    setMode('error', error.message);
    throw error;
  }
}

/** ES/EN/PT: sondeo de conexión: actualiza el modo aunque nadie navegue. */
async function probe() {
  try {
    const response = await fetch('./api/health', { cache: 'no-store' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const servedFromCache = response.headers.get('X-Genesis-Offline') === 'cached';
    setMode(servedFromCache ? 'cached' : 'live');
    if (!servedFromCache) storeLocal('/api/health', await response.clone().json());
    return !servedFromCache;
  } catch {
    const fromCache = await readCacheStorage('/api/health');
    const fromLocal = readLocal('/api/health');
    if (fromCache !== null || fromLocal) setMode('cached');
    else setMode('error');
    return false;
  }
}

async function refreshData() {
  setStatus('refreshing…');
  await probe();
  await route();
}

/* ── Service worker + instalación PWA / Service worker + PWA install ──────── */

async function registerServiceWorker() {
  if (!('serviceWorker' in navigator)) {
    setMode(dataMode.source === 'connecting' ? 'error' : dataMode.source, 'no service worker support');
    return;
  }
  const secure = location.protocol === 'https:' || ['localhost', '127.0.0.1'].includes(location.hostname);
  if (!secure) return; // ES: los SW exigen HTTPS o localhost | EN: SWs require HTTPS or localhost
  try {
    swRegistration = await navigator.serviceWorker.register('./sw.js', { scope: './' });
    navigator.serviceWorker.addEventListener('message', (event) => {
      const { type, shell_entries: shellEntries, api_entries: apiEntries, version } = event.data ?? {};
      if (type === 'CACHE_STATUS') {
        const meta = document.getElementById('meta-cache');
        if (meta) meta.textContent = `sw ${version} · ${shellEntries}+${apiEntries} cached`;
      }
    });
    swRegistration.addEventListener('updatefound', () => {
      const worker = swRegistration.installing;
      worker?.addEventListener('statechange', () => {
        if (worker.state === 'installed' && navigator.serviceWorker.controller) {
          setStatus('app updated — reload to apply');
        }
      });
    });
    setTimeout(() => navigator.serviceWorker.controller?.postMessage({ type: 'CACHE_STATUS' }), 1200);
  } catch (error) {
    // ES: sin SW la app sigue funcionando (localStorage + snapshot). Sin SW la
    //     app sigue funcionando. The app still works without the SW.
    setStatus(`sw unavailable: ${error.message}`);
  }
}

window.addEventListener('beforeinstallprompt', (event) => {
  event.preventDefault();
  installPromptEvent = event;
  const button = document.getElementById('install-btn');
  if (button) button.hidden = false;
});
window.addEventListener('appinstalled', () => {
  installPromptEvent = null;
  const button = document.getElementById('install-btn');
  if (button) button.hidden = true;
  setStatus('app installed on this device');
});

async function installApp() {
  if (!installPromptEvent) {
    setStatus('install not offered by this browser (use the browser menu → Install / Add to Home Screen)');
    return;
  }
  installPromptEvent.prompt();
  const choice = await installPromptEvent.userChoice.catch(() => null);
  setStatus(`install prompt: ${choice?.outcome ?? 'dismissed'}`);
  if (choice?.outcome === 'accepted') installPromptEvent = null;
}

/* ── Navegación / Navigation ──────────────────────────────────────────────── */

const NAV = [
  { group: 'EXPLORE' },
  { id: 'dashboard', label: 'Dashboard', icon: '▦', mode: 'explore' },
  { id: 'sessions', label: 'Sessions', icon: '💬', mode: 'explore' },
  { id: 'timeline', label: 'Timeline', icon: '🕒', mode: 'explore' },
  { id: 'decisions', label: 'Decisions', icon: '◆', mode: 'explore' },
  { id: 'knowledge', label: 'Knowledge search', icon: '⌕', mode: 'explore' },
  { id: 'graph', label: 'Knowledge graph', icon: '🕸', mode: 'explore' },
  { id: 'context', label: 'Context engine', icon: '🧠', mode: 'explore' },
  { group: 'BUILD' },
  { id: 'tasks', label: 'Tasks & roadmap', icon: '▤', mode: 'build' },
  { id: 'requirements', label: 'Requirements', icon: '✓', mode: 'build' },
  { id: 'checkpoints', label: 'Checkpoints', icon: '⛉', mode: 'build' },
  { group: 'EVOLVE' },
  { id: 'evolve', label: 'Lessons & failures', icon: '★', mode: 'evolve' },
  { group: 'LEARN' },
  { id: 'docs', label: 'Documentation', icon: '📚', mode: 'learn' },
  { id: 'api', label: 'API routes', icon: '⇄', mode: 'learn' },
  { id: 'offline', label: 'Offline & install', icon: '📴', mode: 'learn' },
];

const BOTTOM_VIEWS = new Set(['dashboard', 'sessions', 'decisions', 'graph']);

function currentViewId() {
  return (location.hash || '#/dashboard').replace(/^#\//, '').split('/')[0] || 'dashboard';
}

function renderNav(counts = {}, target = null) {
  const list = target ?? document.getElementById('nav');
  if (!list) return;
  list.textContent = '';
  const active = currentViewId();
  for (const item of NAV) {
    if (item.group) {
      list.appendChild(el('li', { class: 'nav-group', text: item.group }));
      continue;
    }
    list.appendChild(el('li', {}, [
      el('a', { class: `nav-link ${active === item.id ? 'is-active' : ''}`, href: `#/${item.id}`, dataset: { view: item.id }, onclick: closeDrawer }, [
        el('span', { text: item.icon }),
        el('span', { text: item.label }),
        counts[item.id] !== undefined ? el('span', { class: 'count', text: String(counts[item.id]) }) : null,
      ]),
    ]));
  }
  const activeItem = NAV.find((entry) => entry.id === active);
  document.querySelectorAll('.mode').forEach((node) => {
    node.classList.toggle('is-active', node.dataset.mode === (activeItem?.mode ?? 'explore'));
  });
  document.querySelectorAll('#bottom-nav .tab').forEach((tab) => {
    tab.classList.toggle('is-active', tab.dataset.view === active);
  });
}

/* ── Cajón móvil / Mobile drawer ──────────────────────────────────────────── */

function openDrawer() {
  document.getElementById('sidebar')?.classList.add('is-open');
  const scrim = document.getElementById('scrim');
  if (scrim) scrim.hidden = false;
  document.getElementById('menu-toggle')?.setAttribute('aria-expanded', 'true');
}
function closeDrawer() {
  document.getElementById('sidebar')?.classList.remove('is-open');
  const scrim = document.getElementById('scrim');
  if (scrim) scrim.hidden = true;
  document.getElementById('menu-toggle')?.setAttribute('aria-expanded', 'false');
  document.getElementById('sheet').hidden = true;
  document.getElementById('more-tab')?.setAttribute('aria-expanded', 'false');
}

function wireChrome() {
  document.getElementById('menu-toggle')?.addEventListener('click', () => {
    const open = document.getElementById('sidebar')?.classList.contains('is-open');
    if (open) closeDrawer(); else openDrawer();
  });
  document.getElementById('scrim')?.addEventListener('click', closeDrawer);
  document.getElementById('refresh-btn')?.addEventListener('click', refreshData);
  document.getElementById('install-btn')?.addEventListener('click', installApp);
  document.getElementById('more-tab')?.addEventListener('click', () => {
    const sheet = document.getElementById('sheet');
    const willOpen = sheet.hidden;
    sheet.hidden = !willOpen;
    document.getElementById('more-tab')?.setAttribute('aria-expanded', String(willOpen));
    if (willOpen) renderNav({}, document.getElementById('sheet-nav'));
  });
  document.getElementById('sheet-close')?.addEventListener('click', () => {
    document.getElementById('sheet').hidden = true;
    document.getElementById('more-tab')?.setAttribute('aria-expanded', 'false');
  });
  document.querySelectorAll('#sheet-nav, #nav').forEach((list) => list.addEventListener('click', () => { document.getElementById('sheet').hidden = true; }));
  window.addEventListener('online', () => probe());
  window.addEventListener('offline', () => setMode('cached', 'browser reports no network'));
  setInterval(probe, 20000);
}

function setStatus(text) {
  const node = document.getElementById('status-text');
  if (node) node.textContent = text;
}

/* ── Componentes / Components ─────────────────────────────────────────────── */

function table(headers, rows) {
  const head = el('thead', {}, [el('tr', {}, headers.map((header) => el('th', { text: String(header) })))]);
  const body = el('tbody', {}, rows.map((row) => el('tr', {}, [].concat(row).map((cell) => el('td', {}, [
    typeof cell === 'string' || typeof cell === 'number' ? document.createTextNode(String(cell)) : cell,
  ])))));
  // ES: envoltorio con scroll horizontal: en móvil las tablas anchas no rompen el
  //     layout, se deslizan. EN: horizontal scroll wrapper so wide tables slide on
  //     mobile instead of breaking the layout. PT: wrapper com scroll horizontal.
  return el('div', { class: 'table-scroll' }, [el('table', {}, [head, body])]);
}

function statCard(label, value, note, percent = null) {
  return el('div', { class: 'stat' }, [
    el('div', { class: 'label', text: label }),
    el('div', { class: 'value', text: String(value) }),
    percent === null
      ? el('div', { class: 'note', text: String(note ?? '') })
      : el('div', {}, [el('div', { class: 'progress' }, [el('span', { style: `width:${Math.min(100, percent)}%` })]), el('div', { class: 'note', text: String(note ?? '') })]),
  ]);
}

/* ── Vistas / Views ───────────────────────────────────────────────────────── */

const VIEWS = {};

VIEWS.dashboard = async () => {
  const [stats, recent, state] = await Promise.all([api('/api/stats'), api('/api/recent?limit=5'), api('/api/state')]);
  const summary = stats.state ?? {};
  const processing = stats.processing ?? {};
  const graph = stats.graph ?? {};
  const percent = Number(summary.progress_percent ?? 0);

  return [
    el('h1', { text: 'Project dashboard' }),
    el('p', { class: 'subtitle', text: 'Level 5 CONTROL in one screen: where the project is, what it knows, what is blocking it and what to do next. Works in desktop and mobile, online and offline.' }),

    el('div', { class: 'grid grid-4' }, [
      statCard('Progress', `${percent}%`, state?.current_phase ?? '—', percent),
      statCard('Decisions', num(processing.decisions), `${num(processing.requirements)} requirements`),
      statCard('Knowledge nodes', num(graph.nodes), `${num(graph.edges)} relations`),
      statCard('Observable events', num(processing.events), `${num(stats.events_on_disk)} on disk`),
    ]),

    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'Data mode' }), el('span', { class: 'hint', text: 'dual-mode: online live / offline cached / snapshot' })]),
      el('div', { class: 'row' }, [
        badge(MODE_COPY[dataMode.source]?.label ?? dataMode.source, dataMode.source === 'live' ? 'green' : dataMode.source === 'error' ? 'red' : 'yellow'),
        el('span', { class: 'mono faint small', text: dataMode.at ? `synced ${timeAgo(dataMode.at)}` : 'never synced' }),
        el('button', { text: 'Refresh', onclick: refreshData }),
      ]),
    ]),

    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'Current position' }), el('span', { class: 'hint', text: 'state.json + tasks.json' })]),
      table(['Field', 'Value'], [
        ['Project', summary.project ?? '—'],
        ['Current phase', summary.current_phase ?? '—'],
        ['Current task', summary.current_task ? `${summary.current_task.id} · ${summary.current_task.title}` : '—'],
        ['Task status', summary.current_task ? badge(summary.current_task.status, statusColor(summary.current_task.status)) : '—'],
        ['Agent', summary.agent_status ?? 'idle'],
        ['Last checkpoint', summary.last_checkpoint?.id ?? 'none'],
        ['Open blocks', String((summary.open_blocks ?? []).length)],
        ['Updated', summary.updated_at ?? '—'],
      ]),
    ]),

    (summary.open_blocks ?? []).length
      ? el('div', { class: 'card' }, [
        el('div', { class: 'card-header' }, [el('strong', { text: 'Open blocks / interruptions' })]),
        ...summary.open_blocks.map((block) => el('div', { class: 'row small' }, [
          badge(block.type ?? block.id ?? 'block', 'red'),
          el('span', { text: block.reason ?? '—' }),
          block.recoverable === false ? badge('not recoverable', 'red') : badge('recoverable', 'green'),
        ])),
      ])
      : null,

    el('h2', { text: 'Knowledge base' }),
    el('div', { class: 'grid grid-4' }, [
      statCard('Sessions', num(processing.sessions), `${num(processing.messages)} messages`),
      statCard('Plans', num(processing.plans), `${num(processing.searches)} searches`),
      statCard('Errors', num(processing.errors), `${num(processing.lessons)} lessons`),
      statCard('Indexed entities', num(processing.indexed_entities), `schema v${stats.database?.schema_version ?? '?'}`),
    ]),

    el('div', { class: 'two-col' }, [
      el('div', { class: 'card' }, [
        el('div', { class: 'card-header' }, [el('strong', { text: 'Recent decisions' })]),
        el('ul', { class: 'list' }, (recent.decisions ?? []).map((decision) => el('li', {}, [
          el('div', { class: 'row' }, [el('strong', { class: 'mono', text: decision.id }), badge(decision.status, statusColor(decision.status)), badge(decision.layer ?? '—')]),
          el('div', { class: 'small muted', text: truncate(decision.decision, 200) }),
        ]))),
      ]),
      el('div', { class: 'card' }, [
        el('div', { class: 'card-header' }, [el('strong', { text: 'Lessons learned' })]),
        el('ul', { class: 'list' }, (recent.lessons ?? []).map((lesson) => el('li', {}, [
          el('div', { class: 'small', text: truncate(lesson.lesson, 170) }),
          lesson.future_rule ? el('div', { class: 'mono faint small', text: `rule → ${lesson.future_rule}` }) : null,
        ]))),
      ]),
    ]),

    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'Most connected knowledge hubs' })]),
      table(['Degree', 'Kind', 'Node'], (graph.hubs ?? []).map((hub) => [String(hub.degree), badge(hub.kind), hub.label])),
    ]),
  ];
};

VIEWS.sessions = async () => {
  const { sessions } = await api('/api/sessions');
  return [
    el('h1', { text: 'Sessions' }),
    el('p', { class: 'subtitle', text: 'Every captured conversation (RAW level). The original text is preserved verbatim; the interpretation lives beside it and can be regenerated at any time.' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Title', 'Messages', 'Format', 'Captured', 'Hash', ''], (sessions ?? []).map((session) => [
        el('span', { class: 'mono', text: session.id }),
        truncate(session.title, 90),
        num(session.message_count),
        badge(session.format ?? '—'),
        String(session.captured_at ?? '').slice(0, 19).replace('T', ' '),
        el('span', { class: 'mono faint', text: session.raw_hash_short ?? '' }),
        el('a', { class: 'btn', href: `#/sessions/${session.id}`, text: 'open' }),
      ])),
    ]),
  ];
};

VIEWS['sessions/:id'] = async (params) => {
  const data = await api(`/api/sessions/${encodeURIComponent(params.id)}`);
  const { session, raw_messages: rawMessages, processed_messages: processed } = data;
  const interpretation = new Map(processed.map((row) => [row.id, row]));

  return [
    el('div', { class: 'row' }, [el('a', { class: 'btn', href: '#/sessions', text: '← sessions' }), el('h1', { text: session.id })]),
    el('p', { class: 'subtitle', text: session.title ?? '' }),
    el('div', { class: 'card' }, [
      table(['Field', 'Value'], [
        ['Source', session.source ?? '—'],
        ['Format detected', session.format ?? '—'],
        ['Messages', num(session.message_count)],
        ['Characters', num(session.chars)],
        ['Integrity hash (SHA-256)', el('span', { class: 'mono small', text: session.raw_hash ?? '—' })],
        ['Captured at', session.captured_at ?? '—'],
        ['Processed at', session.processed_at ?? 'not processed yet'],
      ]),
    ]),
    el('h2', { text: 'Messages (RAW content + interpretation)' }),
    ...rawMessages.map((message) => {
      const parsed = interpretation.get(message.id) ?? {};
      return el('article', { class: 'msg', dataset: { role: message.role } }, [
        el('div', { class: 'msg-head' }, [
          el('strong', { class: 'mono', text: message.id }),
          badge(message.role, message.role === 'assistant' ? 'blue' : 'green'),
          parsed.intent ? badge(`intent: ${parsed.intent}`, 'magenta') : null,
          parsed.language ? badge(parsed.language) : null,
          el('span', { class: 'faint mono', text: `${num(message.chars ?? parsed.chars)} chars · ${num(parsed.words ?? 0)} words` }),
        ]),
        el('div', { class: 'msg-body', text: message.content }),
        parsed.requirements?.length || parsed.terms?.length || parsed.entities?.length
          ? el('div', { class: 'row small', style: 'margin-top:8px' }, [
            ...(parsed.requirements ?? []).slice(0, 3).map((requirement) => badge(`REQ: ${truncate(requirement, 60)}`, 'yellow')),
            ...(parsed.terms ?? []).slice(0, 6).map((term) => badge(term, 'blue')),
            ...(parsed.entities ?? []).slice(0, 6).map((entity) => badge(entity, 'magenta')),
          ])
          : null,
      ]);
    }),
  ];
};

VIEWS.timeline = async () => {
  const data = await api('/api/timeline?limit=400');
  const iconFor = (type) => ({
    SESSION_STARTED: '▶', SESSION_ENDED: '■', MESSAGE_RECEIVED: '✉', DECISION_MADE: '◆', PLAN_CREATED: '▤',
    SEARCH_PERFORMED: '⌕', ERROR_DETECTED: '✗', LESSON_CREATED: '★', CHECKPOINT_CREATED: '⛉',
    INTERRUPTION_RAISED: '⚡', RECOVERY_COMPLETED: '↺', KNOWLEDGE_EXTRACTED: '⚙', STATE_UPDATED: '↻',
    TOOL_EXECUTED: '⚒', BUILD_COMPLETED: '✓', CONTEXT_BUILT: '🧠', FILE_CHANGED: '✎', TEST_PASSED: '✓', TEST_FAILED: '✗',
  }[type] ?? '·');
  const colorFor = (type) => (type.includes('ERROR') || type.includes('INTERRUPTION') || type === 'TEST_FAILED' ? 'red'
    : type.includes('LESSON') || type.includes('RECOVERY') || type === 'TEST_PASSED' || type === 'BUILD_COMPLETED' ? 'green'
      : type === 'DECISION_MADE' ? 'magenta' : 'blue');

  const days = [...(data.days ?? [])].reverse();
  return [
    el('h1', { text: 'Timeline' }),
    el('p', { class: 'subtitle', text: 'Section 10 of the architecture: the chronological history of everything observable. This is what makes "how did the project reach its current state?" answerable.' }),
    el('div', { class: 'row small faint' }, [el('span', { text: `${data.count} events across ${days.length} day(s)` })]),
    ...days.map((day) => el('div', {}, [
      el('div', { class: 'timeline-day', text: day }),
      ...(data.by_day[day] ?? []).slice().reverse().map((event) => el('div', { class: 'timeline-item' }, [
        el('span', { class: 'ts', text: String(event.ts).slice(11, 19) }),
        el('span', { class: `badge badge-${colorFor(event.type)}`, text: iconFor(event.type) }),
        el('span', { class: 'type', text: event.type }),
        el('span', { class: 'detail small muted', text: truncate(JSON.stringify(event.payload ?? {}), 220) }),
      ])),
    ])),
  ];
};

VIEWS.decisions = async () => {
  const { decisions } = await api('/api/decisions');
  return [
    el('h1', { text: 'Decision Traces' }),
    el('p', { class: 'subtitle', text: 'DEC-00003: we do not store a model’s private reasoning. We store an explainable trace — objective, context, constraints, alternatives, decision, justification, consequence, status.' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Status', 'Layer', 'Decision', ''], decisions.map((decision) => [
        el('span', { class: 'mono', text: decision.id }),
        badge(decision.status ?? '—', statusColor(decision.status)),
        badge(decision.layer ?? '—'),
        truncate(decision.decision, 150),
        el('a', { class: 'btn', href: `#/decisions/${decision.id}`, text: 'trace' }),
      ])),
    ]),
  ];
};

VIEWS['decisions/:id'] = async (params) => {
  const decision = await api(`/api/decisions/${encodeURIComponent(params.id)}`);
  const provenance = await api(`/api/decisions/${encodeURIComponent(params.id)}/provenance`).catch(() => null);
  const fields = [
    ['Objective (EN)', decision.objective_en], ['Objective (ES)', decision.objective_es], ['Objective (PT)', decision.objective_pt],
    ['Context', decision.context], ['Justification', decision.justification], ['Consequence', decision.consequence], ['Evidence', decision.evidence],
  ];

  return [
    el('div', { class: 'row' }, [el('a', { class: 'btn', href: '#/decisions', text: '← decisions' }), el('h1', { text: decision.id }), badge(decision.status, statusColor(decision.status)), badge(decision.layer ?? '—')]),
    el('p', { class: 'subtitle', text: decision.decision ?? '' }),

    el('div', { class: 'two-col' }, [
      el('div', {}, [
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Trace' })]),
          table(['Field', 'Value'], fields.filter(([, value]) => value).map(([label, value]) => [label, el('span', { class: 'small', text: String(value) })])),
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Constraints' })]),
          el('ul', { class: 'list small' }, (decision.constraints ?? []).map((item) => el('li', { text: item }))),
          (decision.constraints ?? []).length ? null : el('p', { class: 'empty', text: 'none recorded' }),
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Alternatives considered' }), el('span', { class: 'hint', text: `${(decision.alternatives ?? []).length} options` })]),
          table(['', 'Option', 'Why rejected'], (decision.alternatives ?? []).map((alternative) => [
            alternative.selected ? badge('SELECTED', 'green') : el('span', { class: 'mono', text: alternative.id ?? '•' }),
            alternative.option ?? '',
            el('span', { class: 'small muted', text: alternative.rejected_because ?? '—' }),
          ])),
        ]),
      ]),
      el('div', {}, [
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Provenance chain' }), el('span', { class: 'hint', text: 'section 15' })]),
          provenance?.chains?.length
            ? provenance.chains.map((chain) => el('div', { class: 'small' }, [
              el('div', { text: `Searches: ${chain.searches.length ? chain.searches.map((s) => s.id).join(', ') : '—'}` }),
              el('div', { text: `Sources: ${chain.sources.length}` }),
              el('ul', { class: 'list small' }, chain.sources.slice(0, 6).map((source) => el('li', {}, [el('a', { href: source, target: '_blank', rel: 'noreferrer', text: truncate(source, 70) })]))),
              el('div', { class: 'faint', text: `Implementation actions: ${chain.implementation.length}` }),
              el('div', { class: 'faint', text: `Related lessons: ${chain.lessons.length}` }),
            ]))
            : el('p', { class: 'empty', text: 'No searches linked to this decision yet.' }),
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Related' })]),
          el('div', { class: 'row' }, (decision.related ?? []).map((item) => badge(item, 'magenta'))),
          (decision.related ?? []).length ? null : el('p', { class: 'empty', text: 'none' }),
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Rendered trace' })]),
          el('pre', { text: decision.rendered?.en ?? '' }),
        ]),
      ]),
    ]),
  ];
};

VIEWS.knowledge = async () => {
  const stats = await api('/api/stats');
  const facets = stats.facets ?? {};
  const tags = stats.top_tags ?? [];

  const resultsBox = el('div', {});
  const input = el('input', { type: 'search', placeholder: 'Search the whole knowledge base… (e.g. sqlite, offline, checkpoint)', id: 'q', enterkeyhint: 'search' });
  const typeSelect = el('select', { id: 'type' }, [
    el('option', { value: '', text: 'all entity types' }),
    ...Object.entries(facets).map(([type, count]) => el('option', { value: type, text: `${type} (${count})` })),
  ]);
  const button = el('button', { class: 'primary', text: 'Search' });

  const run = async () => {
    resultsBox.textContent = '';
    resultsBox.appendChild(el('p', { class: 'loading', text: 'searching FTS5 index…' }));
    try {
      const result = await api(`/api/search?q=${encodeURIComponent(input.value)}&limit=25${typeSelect.value ? `&type=${encodeURIComponent(typeSelect.value)}` : ''}`);
      const results = result.results ?? [];
      resultsBox.textContent = '';
      if (!results.length) {
        resultsBox.appendChild(el('p', { class: 'empty', text: 'No results. Run `genesis process` first if the knowledge base is empty.' }));
        return;
      }
      resultsBox.appendChild(el('div', { class: 'card' }, [
        el('div', { class: 'card-header' }, [el('strong', { text: `${results.length} result(s)` }), el('span', { class: 'hint', text: 'FTS5 bm25 ranking, diacritics removed' })]),
        el('ul', { class: 'list' }, results.map((hit) => el('li', {}, [
          el('div', { class: 'row' }, [
            el('span', { class: 'mono faint', text: `#${hit.rank}` }),
            badge(hit.type, 'blue'),
            hit.id.startsWith('DEC-')
              ? el('a', { class: 'mono', href: `#/decisions/${hit.id}`, text: hit.id })
              : el('span', { class: 'mono', text: hit.id }),
            hit.score === null ? null : el('span', { class: 'mono faint', text: `bm25 ${hit.score}` }),
          ]),
          el('div', { class: 'small', text: truncate(hit.title, 190) }),
          el('div', { class: 'small muted' }, [highlight(hit.snippet)]),
        ]))),
      ]));
    } catch (error) {
      resultsBox.textContent = '';
      resultsBox.appendChild(el('div', { class: 'error-box', text: error.message }));
    }
  };

  button.addEventListener('click', run);
  input.addEventListener('keydown', (event) => { if (event.key === 'Enter') run(); });
  typeSelect.addEventListener('change', run);

  const query = new URLSearchParams(location.hash.split('?')[1] ?? '').get('q');
  if (query) { input.value = query; setTimeout(run, 0); }

  return [
    el('h1', { text: 'Knowledge search' }),
    el('p', { class: 'subtitle', text: 'One FTS5 index across every entity type. Diacritics are removed, so "decisión", "decisao" and "decision" all match the same rows — essential in a trilingual project.' }),
    el('div', { class: 'toolbar' }, [input, typeSelect, button]),
    resultsBox,
    el('h2', { text: 'Indexed entities by type' }),
    el('div', { class: 'row' }, Object.entries(facets).map(([type, count]) => badge(`${type}: ${count}`, 'blue'))),
    el('h2', { text: 'Top tags' }),
    el('div', { class: 'row' }, tags.map((tag) => el('button', { text: `${tag.tag} ${tag.n}`, onclick: () => { input.value = tag.tag; run(); window.scrollTo({ top: 0 }); } }))),
  ];
};

VIEWS.graph = async () => {
  const graph = await api('/api/graph?limit=220');
  const canvas = el('canvas', { id: 'graph-canvas' });
  const detail = el('div', { class: 'card' }, [el('p', { class: 'empty', text: 'Tap a node to see its full profile (what it is, why it exists, where it is used, problems, lessons, code, sessions, sources). Pinch-free: drag to pan, wheel to zoom.' })]);

  const kindColors = {
    decision: '#c792ea', technology: '#4fd1c5', requirement: '#e3b341', task: '#7aa2f7', phase: '#ff9e64',
    lesson: '#56d364', mistake: '#f85149', reference: '#8be9fd', category: '#64748b', session: '#93a2b8', architecture: '#ffffff',
  };

  const legend = el('div', { class: 'legend' }, Object.entries(kindColors)
    .filter(([kind]) => graph.nodes.some((node) => node.kind === kind))
    .map(([kind, color]) => el('span', { style: `color:${color}`, text: kind })));

  const nodes = graph.nodes.map((node, index) => ({
    ...node,
    x: Math.cos((index / graph.nodes.length) * Math.PI * 2) * 220 + 400,
    y: Math.sin((index / graph.nodes.length) * Math.PI * 2) * 180 + 260,
    vx: 0, vy: 0,
    radius: 4 + Math.min(9, (graph.edges.filter((edge) => edge.source === node.id || edge.target === node.id).length) * 0.8),
  }));
  const byId = new Map(nodes.map((node) => [node.id, node]));
  const edges = graph.edges.map((edge) => ({ source: byId.get(edge.source), target: byId.get(edge.target), weight: edge.weight, relation: edge.relation })).filter((edge) => edge.source && edge.target);

  const context = canvas.getContext('2d');
  let transform = { x: 0, y: 0, scale: 1 };
  let hovered = null;
  let alpha = 1;
  let running = true;

  const resize = () => {
    const rect = canvas.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.max(320, rect.width * dpr);
    canvas.height = Math.max(320, rect.height * dpr);
    context.setTransform(dpr, 0, 0, dpr, 0, 0);
  };

  const tick = () => {
    if (!running) return;
    const rect = canvas.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;

    for (let i = 0; i < nodes.length; i += 1) {
      for (let j = i + 1; j < nodes.length; j += 1) {
        const a = nodes[i]; const b = nodes[j];
        let dx = b.x - a.x; let dy = b.y - a.y;
        let distance = Math.sqrt(dx * dx + dy * dy) || 0.01;
        if (distance > 420) continue;
        const force = (2600 / (distance * distance)) * alpha;
        dx /= distance; dy /= distance;
        a.vx -= dx * force; a.vy -= dy * force;
        b.vx += dx * force; b.vy += dy * force;
      }
    }
    for (const edge of edges) {
      const dx = edge.target.x - edge.source.x;
      const dy = edge.target.y - edge.source.y;
      const distance = Math.sqrt(dx * dx + dy * dy) || 0.01;
      const desired = 96 + 40 / Math.max(1, edge.weight);
      const force = ((distance - desired) / distance) * 0.035 * alpha;
      edge.source.vx += dx * force; edge.source.vy += dy * force;
      edge.target.vx -= dx * force; edge.target.vy -= dy * force;
    }
    for (const node of nodes) {
      node.vx += (width / 2 - node.x) * 0.0016 * alpha;
      node.vy += (height / 2 - node.y) * 0.0016 * alpha;
      node.vx *= 0.86; node.vy *= 0.86;
      node.x += node.vx; node.y += node.vy;
    }
    alpha = Math.max(0.02, alpha * 0.995);

    context.clearRect(0, 0, width, height);
    context.save();
    context.translate(transform.x, transform.y);
    context.scale(transform.scale, transform.scale);

    for (const edge of edges) {
      context.beginPath();
      context.moveTo(edge.source.x, edge.source.y);
      context.lineTo(edge.target.x, edge.target.y);
      context.strokeStyle = `rgba(120,150,190,${Math.min(0.42, 0.06 + edge.weight * 0.05)})`;
      context.lineWidth = Math.min(2.6, 0.4 + edge.weight * 0.35);
      context.stroke();
    }
    for (const node of nodes) {
      const isHover = node === hovered;
      context.beginPath();
      context.arc(node.x, node.y, node.radius + (isHover ? 2 : 0), 0, Math.PI * 2);
      context.fillStyle = kindColors[node.kind] ?? '#93a2b8';
      context.globalAlpha = isHover ? 1 : 0.86;
      context.fill();
      context.globalAlpha = 1;
      if (isHover || node.radius > 8.5) {
        context.fillStyle = 'rgba(230,237,246,0.92)';
        context.font = '10px ui-monospace, monospace';
        context.fillText(truncate(node.label, 34), node.x + node.radius + 4, node.y + 3);
      }
    }
    context.restore();
    requestAnimationFrame(tick);
  };

  const pick = (event) => {
    const rect = canvas.getBoundingClientRect();
    const x = (event.clientX - rect.left - transform.x) / transform.scale;
    const y = (event.clientY - rect.top - transform.y) / transform.scale;
    let best = null; let bestDistance = Infinity;
    for (const node of nodes) {
      const distance = Math.hypot(node.x - x, node.y - y);
      if (distance < node.radius + 9 && distance < bestDistance) { best = node; bestDistance = distance; }
    }
    return best;
  };

  // ES: puntero unificado = ratón + dedo. Pointer Events cubren ambos con un solo
  //     juego de listeners. EN: unified pointer = mouse + finger; Pointer Events
  //     cover both with one set of listeners. PT: ponteiro unificado.
  let pointerState = null;
  canvas.addEventListener('pointerdown', (event) => {
    canvas.setPointerCapture?.(event.pointerId);
    pointerState = { x: event.clientX, y: event.clientY, moved: 0, node: pick(event) };
    hovered = pointerState.node;
  });
  canvas.addEventListener('pointermove', (event) => {
    if (!pointerState) { hovered = pick(event); return; }
    const dx = event.clientX - pointerState.x;
    const dy = event.clientY - pointerState.y;
    pointerState.moved += Math.abs(dx) + Math.abs(dy);
    if (!pointerState.node) { transform.x += dx; transform.y += dy; }
    pointerState.x = event.clientX; pointerState.y = event.clientY;
  });
  canvas.addEventListener('pointerup', async (event) => {
    const tapped = pointerState?.node ?? null;
    const wasDrag = (pointerState?.moved ?? 0) > 8;
    pointerState = null;
    if (!tapped || wasDrag) return;
    detail.textContent = '';
    detail.appendChild(el('p', { class: 'loading', text: `loading profile of ${tapped.label}…` }));
    try {
      const profile = await api(`/api/graph/node/${encodeURIComponent(tapped.id)}`);
      detail.textContent = '';
      detail.appendChild(el('div', { class: 'card-header' }, [el('strong', { text: truncate(profile.label, 60) }), badge(profile.kind, 'blue')]));
      detail.appendChild(table(['Field', 'Value'], [
        ['What is', profile.what_is], ['Why exists', profile.why_exists], ['Where used', profile.where_used],
        ['How built', profile.how_built], ['Problems', profile.problems], ['Learned', profile.learned],
        ['Code refs', (profile.code_refs ?? []).join(', ')], ['Sessions', (profile.sessions ?? []).join(', ')],
        ['Sources', (profile.sources ?? []).join(' ')],
      ].filter(([, value]) => value && String(value).length).map(([label, value]) => [label, el('span', { class: 'small', text: truncate(value, 260) })])));
      detail.appendChild(el('h3', { text: `Relations (${profile.relations.outgoing.length + profile.relations.incoming.length})` }));
      detail.appendChild(el('ul', { class: 'list small' }, [...profile.relations.outgoing, ...profile.relations.incoming].slice(0, 18)
        .map((edge) => el('li', { text: `${edge.direction === 'out' ? '→' : '←'} ${edge.relation} · ${truncate(edge.node.label, 58)} (w${edge.weight})` }))));
    } catch (error) {
      detail.textContent = '';
      detail.appendChild(el('div', { class: 'error-box', text: error.message }));
    }
  });
  canvas.addEventListener('pointercancel', () => { pointerState = null; });
  canvas.addEventListener('wheel', (event) => {
    event.preventDefault();
    const factor = event.deltaY < 0 ? 1.12 : 0.89;
    transform.scale = Math.min(3.5, Math.max(0.25, transform.scale * factor));
  }, { passive: false });

  // ES: pellizco con dos dedos (zoom táctil). EN: two-finger pinch zoom.
  const touches = new Map();
  canvas.addEventListener('touchstart', (event) => { for (const touch of event.changedTouches) touches.set(touch.identifier, touch); }, { passive: true });
  canvas.addEventListener('touchmove', (event) => {
    if (event.touches.length !== 2) return;
    event.preventDefault();
    const [a, b] = [...event.touches];
    const distance = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
    if (touches.size === 2) {
      const previous = [...touches.values()];
      const previousDistance = Math.hypot(previous[0].clientX - previous[1].clientX, previous[0].clientY - previous[1].clientY);
      if (previousDistance > 0) transform.scale = Math.min(3.5, Math.max(0.25, transform.scale * (distance / previousDistance)));
    }
    touches.clear();
    for (const touch of event.touches) touches.set(touch.identifier, touch);
  }, { passive: false });
  canvas.addEventListener('touchend', (event) => { for (const touch of event.changedTouches) touches.delete(touch.identifier); }, { passive: true });

  setTimeout(() => { resize(); tick(); }, 0);
  window.addEventListener('resize', resize);
  window.addEventListener('hashchange', () => { running = false; }, { once: true });

  return [
    el('h1', { text: 'Knowledge graph' }),
    el('p', { class: 'subtitle', text: `${graph.stats?.nodes ?? 0} nodes and ${graph.stats?.edges ?? 0} relations, laid out by a force simulation written from scratch. Desktop: drag to pan, wheel to zoom. Mobile: one finger pans, two fingers pinch.` }),
    legend,
    el('div', { class: 'two-col' }, [canvas, detail]),
    el('h2', { text: 'Relations by type' }),
    el('div', { class: 'row' }, Object.entries(graph.stats?.by_relation ?? {}).map(([relation, count]) => badge(`${relation}: ${count}`, 'magenta'))),
  ];
};

VIEWS.context = async () => {
  const [json, text, markdown] = await Promise.all([
    api('/api/context'),
    api('/api/context?format=text'),
    api('/api/context?format=md'),
  ]);

  const copyButton = el('button', { class: 'primary', text: 'Copy Markdown (paste into any AI chat)' });
  copyButton.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      copyButton.textContent = 'Copied ✓';
      setTimeout(() => { copyButton.textContent = 'Copy Markdown (paste into any AI chat)'; }, 1800);
    } catch {
      copyButton.textContent = 'Clipboard blocked — select the text below';
    }
  });

  return [
    el('h1', { text: 'Context Engine' }),
    el('p', { class: 'subtitle', text: 'Section 8: when a new session starts, the system retrieves PROJECT STATE + CURRENT TASK + LAST CHECKPOINT + RELEVANT DECISIONS + FAILED ATTEMPTS + KNOWN CONSTRAINTS + REQUIRED FILES. This removes almost all repetitive context.' }),
    el('div', { class: 'toolbar' }, [copyButton, el('span', { class: 'faint small', text: `generated ${json.generated_at}` })]),
    el('div', { class: 'two-col' }, [
      el('div', { class: 'card' }, [el('div', { class: 'card-header' }, [el('strong', { text: 'Rendered context (plain text)' })]), el('pre', { text })]),
      el('div', {}, [
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'At a glance' })]),
          table(['Field', 'Value'], [
            ['Progress', `${json.progress?.percent ?? 0}%`],
            ['Phase', json.current_phase?.name ?? '—'],
            ['Task', json.current_task?.title ?? '—'],
            ['Checkpoint', json.last_checkpoint?.id ?? 'none'],
            ['Relevant decisions', String((json.relevant_decisions ?? []).length)],
            ['Failed attempts', String((json.failed_attempts ?? []).length)],
            ['Hard constraints', String((json.known_constraints?.hard_policies ?? []).length)],
            ['Files in scope', String((json.required_files ?? []).length)],
          ]),
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Next recommended action' })]),
          el('p', { class: 'small', text: typeof json.next_recommended_action === 'object' ? json.next_recommended_action?.en ?? '' : json.next_recommended_action ?? '—' }),
          typeof json.next_recommended_action === 'object' && json.next_recommended_action
            ? el('div', { class: 'small faint' }, [el('div', { text: `ES · ${json.next_recommended_action.es}` }), el('div', { text: `PT · ${json.next_recommended_action.pt}` })])
            : null,
        ]),
        el('div', { class: 'card' }, [
          el('div', { class: 'card-header' }, [el('strong', { text: 'Remaining roadmap' })]),
          el('ul', { class: 'list small' }, (json.roadmap_remaining ?? []).map((phase) => el('li', {}, [
            el('span', { class: 'mono', text: phase.id }), ' ', badge(phase.status, statusColor(phase.status)), ' ', phase.name,
          ]))),
        ]),
      ]),
    ]),
  ];
};

VIEWS.tasks = async () => {
  const [tasks, roadmap] = await Promise.all([api('/api/tasks'), api('/api/roadmap')]);
  return [
    el('h1', { text: 'Tasks & roadmap' }),
    el('p', { class: 'subtitle', text: 'Each task lives in a finite state machine (section 23). Illegal jumps are rejected: a task cannot go from "discovered" to "completed" without passing through "verifying". That is what makes the progress percentage trustworthy.' }),
    el('h2', { text: 'Phases' }),
    el('div', { class: 'card' }, [
      table(['Phase', 'Name', 'Status', 'Weight', 'Deliverables', 'Exit criteria'], (roadmap.phases ?? []).map((phase) => [
        el('span', { class: 'mono', text: phase.id }), phase.name, badge(phase.status, statusColor(phase.status)), String(phase.weight ?? 0),
        el('span', { class: 'small muted', text: (phase.deliverables ?? []).join(' · ') }),
        el('span', { class: 'small faint', text: truncate(phase.exit_criteria, 130) }),
      ])),
    ]),
    el('h2', { text: 'Tasks' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Status', 'Progress', 'Phase', 'Layer', 'Title'], (tasks.tasks ?? []).map((task) => [
        el('span', { class: 'mono', text: task.id }),
        badge(task.status, statusColor(task.status)),
        el('div', { style: 'min-width:90px' }, [el('div', { class: 'progress' }, [el('span', { style: `width:${Math.min(100, task.progress ?? 0)}%` })])]),
        el('span', { class: 'mono faint', text: task.phase ?? '—' }),
        badge(task.layer ?? '—'),
        truncate(task.title, 110),
      ])),
    ]),
  ];
};

VIEWS.requirements = async () => {
  const data = await api('/api/requirements');
  return [
    el('h1', { text: 'Requirements' }),
    el('p', { class: 'subtitle', text: 'Requirements extracted from the manifest and from the conversations, with their change history. A requirement that changed without anybody noticing is the most expensive kind.' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Priority', 'Status', 'Layer', 'Requirement', 'Acceptance'], (data.requirements ?? []).map((requirement) => [
        el('span', { class: 'mono', text: requirement.id }),
        badge(requirement.priority ?? '—', requirement.priority === 'critical' ? 'red' : requirement.priority === 'high' ? 'orange' : ''),
        badge(requirement.status ?? '—', statusColor(requirement.status)),
        badge(requirement.layer ?? '—'),
        el('span', { class: 'small', text: truncate(requirement.title, 150) }),
        el('span', { class: 'small faint', text: truncate(requirement.acceptance, 130) }),
      ])),
    ]),
    el('h2', { text: 'Change history' }),
    (data.changes ?? []).length
      ? el('div', { class: 'card' }, [table(['Change', 'Requirement', 'Field', 'Before', 'After'], data.changes.map((change) => [change.id, change.requirement_id, change.field, change.before_value, change.after_value]))])
      : el('p', { class: 'empty', text: 'No requirement has changed yet.' }),
  ];
};

VIEWS.checkpoints = async () => {
  const data = await api('/api/checkpoints');
  return [
    el('h1', { text: 'Checkpoints & recovery' }),
    el('p', { class: 'subtitle', text: 'Section 22 and POL-0003: snapshot before any risky mutation, diff before restoring, never overwrite blindly. Rollback from the CLI with `genesis rollback <id>`.' }),
    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: `Latest: ${data.latest?.id ?? 'none'}` }), el('span', { class: 'hint', text: `${data.count} snapshots` })]),
      table(['ID', 'Label', 'Created', 'Progress', 'Task', 'Blocks'], (data.checkpoints ?? []).map((checkpoint) => [
        el('span', { class: 'mono', text: checkpoint.id }),
        checkpoint.label ?? '—',
        String(checkpoint.created_at ?? '').slice(0, 19).replace('T', ' '),
        `${checkpoint.summary?.progress_percent ?? '—'}%`,
        el('span', { class: 'mono faint', text: checkpoint.summary?.current_task ?? '—' }),
        String(checkpoint.summary?.open_blocks ?? 0),
      ])),
    ]),
    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'Recovery capabilities' })]),
      el('div', { class: 'row' }, ['checkpoint', 'rollback', 'resume', 'retry', 'recover', 'skip', 'pause', 'continue'].map((capability) => badge(capability, 'green'))),
      el('p', { class: 'small muted', text: 'Implemented in Phase 0-2: checkpoint, rollback, resume, diff. The rest arrive with the agent in Phase 5.' }),
    ]),
  ];
};

VIEWS.evolve = async () => {
  const [data, interruptions] = await Promise.all([api('/api/lessons'), api('/api/interruptions')]);
  return [
    el('h1', { text: 'Lessons, failures & proposed rules' }),
    el('p', { class: 'subtitle', text: 'EVOLVE mode and section 24: ERROR → ANALYSIS → RECOVERY → LESSON → RULE CREATED → PRECHECK NEXT TIME. That is operational learning, not just memory: the system behaves differently next time.' }),
    el('h2', { text: 'Lessons' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Source', 'Lesson', 'Rule created'], (data.lessons ?? []).map((lesson) => [
        el('span', { class: 'mono', text: lesson.id }),
        badge(lesson.source_type ?? '—', lesson.source_type === 'error' ? 'red' : 'green'),
        el('span', { class: 'small', text: truncate(lesson.lesson, 220) }),
        lesson.future_rule ? badge(lesson.future_rule, 'yellow') : el('span', { class: 'faint', text: '—' }),
      ])),
    ]),
    el('h2', { text: 'Errors and their recovery cycle' }),
    el('div', { class: 'card' }, [
      table(['ID', 'Severity', 'Error', 'Analysis', 'Recovery', 'Resolved'], (data.errors ?? []).map((error) => [
        el('span', { class: 'mono', text: error.id }),
        badge(error.severity ?? '—', error.severity === 'critical' || error.severity === 'high' ? 'red' : 'yellow'),
        el('span', { class: 'small', text: truncate(error.message, 150) }),
        el('span', { class: 'small muted', text: truncate(error.analysis, 150) }),
        el('span', { class: 'small muted', text: truncate(error.recovery, 150) }),
        error.resolved ? badge('resolved', 'green') : badge('open', 'red'),
      ])),
    ]),
    el('h2', { text: 'Interruptions ("cortes")' }),
    (interruptions.interruptions ?? []).length
      ? el('div', { class: 'card' }, [table(['ID', 'Type', 'Layer', 'Reason', 'Impact', 'Status'], interruptions.interruptions.map((item) => [item.id, badge(item.type, 'red'), item.layer ?? '—', truncate(item.reason, 140), item.impact, badge(item.status, statusColor(item.status))]))])
      : el('div', { class: 'card' }, [el('p', { class: 'small muted', text: 'No interruption events stored in the database yet. The taxonomy (blocked, failed, interrupted, waiting_user, dependency_missing, tool_error, ambiguity, conflict, resource_limit, security_stop, scope_change) is implemented in core/event-bus and used by the CLI.' })]),
  ];
};

VIEWS.docs = async () => {
  const [manifest, roadmap] = await Promise.all([api('/api/manifest'), api('/api/roadmap')]);
  const levels = manifest?.architecture?.levels ?? [];
  const layers = manifest?.architecture?.layers ?? [];
  return [
    el('h1', { text: 'Documentation & architecture' }),
    el('p', { class: 'subtitle', text: 'Phase 3 (Documentation Engine) will render all of this automatically from the knowledge base. Meanwhile, the control plane is already the documentation: it is structured, versioned and queryable.' }),
    el('h2', { text: 'The pipeline' }),
    el('div', { class: 'card' }, [el('div', { class: 'row' }, (manifest?.architecture?.pipeline ?? []).map((step, index) => el('span', {}, [badge(step, 'blue'), index < manifest.architecture.pipeline.length - 1 ? el('span', { class: 'faint', text: ' → ' }) : null])))]),
    el('h2', { text: 'Five data levels (DEC-00001)' }),
    el('div', { class: 'card' }, [table(['Level', 'ID', 'Path', 'Purpose'], levels.map((level) => [String(level.level), badge(level.id, 'green'), el('span', { class: 'mono small', text: level.path }), el('span', { class: 'small', text: level.purpose })]))]),
    el('h2', { text: 'Eleven build layers' }),
    el('div', { class: 'card' }, [el('div', { class: 'row' }, layers.map((layer) => badge(`L${layer.layer} ${layer.id}`, 'magenta')))]),
    el('h2', { text: 'Agent loop (Phase 5)' }),
    el('div', { class: 'card' }, [el('div', { class: 'row' }, (manifest?.architecture?.agent_loop ?? []).map((step, index) => el('span', {}, [badge(step, step === 'contextualize' ? 'green' : ''), index < manifest.architecture.agent_loop.length - 1 ? el('span', { class: 'faint', text: ' → ' }) : null]))), el('p', { class: 'small faint', text: 'POL-0006: contextualize comes BEFORE reasoning. Ask "what do we already know?" before "what must I do?".' })]),
    el('h2', { text: 'Mutation protocol (POL-0002)' }),
    el('div', { class: 'card' }, [el('div', { class: 'row' }, (manifest?.architecture?.mutation_protocol ?? []).map((step) => badge(step, 'orange')))]),
    el('h2', { text: 'Roadmap phases' }),
    el('div', { class: 'card' }, [table(['Phase', 'Name', 'Status', 'Deliverables'], (roadmap.phases ?? []).map((phase) => [el('span', { class: 'mono', text: phase.id }), phase.name, badge(phase.status, statusColor(phase.status)), el('span', { class: 'small muted', text: (phase.deliverables ?? []).join(' · ') })]))]),
    el('h2', { text: 'Anti-goals' }),
    el('div', { class: 'card' }, [el('ul', { class: 'list small' }, (manifest?.vision?.anti_goals ?? []).map((goal) => el('li', { text: goal })))]),
  ];
};

VIEWS.api = async () => {
  const routes = await api('/api/routes');
  return [
    el('h1', { text: 'API routes' }),
    el('p', { class: 'subtitle', text: 'The seam of DEC-00005: this offline console and the future Next.js app consume exactly the same contract. Served by node:http with zero dependencies.' }),
    el('div', { class: 'card' }, [
      table(['Method', 'Route', 'Description'], (routes.routes ?? routes ?? []).map((route) => [
        badge(route.method, route.method === 'GET' ? 'green' : 'yellow'),
        el('a', { class: 'mono', href: route.pattern.includes(':') ? '#/api' : route.pattern, target: route.pattern.includes(':') ? null : '_blank', rel: 'noreferrer', text: route.pattern }),
        el('span', { class: 'small muted', text: route.description }),
      ])),
    ]),
  ];
};

VIEWS.offline = async () => {
  const health = await api('/api/health').catch(() => null);
  const cacheInfo = await new Promise((resolve) => {
    if (!navigator.serviceWorker?.controller) { resolve(null); return; }
    const handler = (event) => {
      if (event.data?.type === 'CACHE_STATUS') {
        navigator.serviceWorker.removeEventListener('message', handler);
        resolve(event.data);
      }
    };
    navigator.serviceWorker.addEventListener('message', handler);
    navigator.serviceWorker.controller.postMessage({ type: 'CACHE_STATUS' });
    setTimeout(() => { navigator.serviceWorker.removeEventListener('message', handler); resolve(null); }, 1500);
  });

  const purgeButton = el('button', { text: 'Purge offline cache' });
  purgeButton.addEventListener('click', async () => {
    navigator.serviceWorker?.controller?.postMessage({ type: 'PURGE_API_CACHE' });
    localStorage.clear();
    setStatus('offline cache purged — next visit offline will use the snapshot');
    await refreshData();
  });

  return [
    el('h1', { text: 'Offline & install' }),
    el('p', { class: 'subtitle', text: 'This app is a PWA: installable on desktop and mobile, usable with and without connection. Here you can see which mode is active and manage the offline copy.' }),
    el('div', { class: 'grid grid-3' }, [
      statCard('Data mode', MODE_COPY[dataMode.source]?.pill ?? dataMode.source, dataMode.at ? `synced ${timeAgo(dataMode.at)}` : 'never synced'),
      statCard('Service worker', navigator.serviceWorker?.controller ? 'active' : swRegistration ? 'registered' : 'unavailable', cacheInfo ? `version ${cacheInfo.version}` : 'no CACHE_STATUS yet'),
      statCard('Cached entries', cacheInfo ? `${cacheInfo.shell_entries} shell + ${cacheInfo.api_entries} api` : '—', 'shell + last-known API responses'),
    ]),
    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'How the two modes work' })]),
      el('ul', { class: 'list small' }, [
        el('li', {}, [badge('ONLINE', 'green'), ' the API answers; every successful response is also stored as the offline copy.']),
        el('li', {}, [badge('OFFLINE', 'yellow'), ' the service worker serves the shell and the last good response of each request; the banner shows the sync time.']),
        el('li', {}, [badge('SNAPSHOT', 'yellow'), ' if the API was never reached, snapshot.json (bundled with the repo) feeds every view.']),
        el('li', {}, [badge('INSTALL', 'blue'), ' desktop: browser menu → Install app. Mobile: Add to Home Screen. The install button appears when the browser offers it.']),
      ]),
      el('div', { class: 'row', style: 'margin-top:12px' }, [
        el('button', { class: 'primary', text: 'Install app', onclick: installApp, hidden: !installPromptEvent }),
        el('button', { text: 'Refresh now', onclick: refreshData }),
        purgeButton,
      ]),
    ]),
    el('div', { class: 'card' }, [
      el('div', { class: 'card-header' }, [el('strong', { text: 'Environment' })]),
      table(['Field', 'Value'], [
        ['API service', health?.service ?? 'unreachable'],
        ['node', health?.node ?? '—'],
        ['sqlite', health?.sqlite ?? '—'],
        ['dependencies', String(health?.dependencies ?? 0)],
        ['offline_capable', health ? String(health.offline_capable) : '—'],
        ['navigator.onLine', String(navigator.onLine)],
        ['storage keys', String(Object.keys(localStorage).filter((key) => key.startsWith('genesis:')).length)],
      ]),
    ]),
  ];
};

/* ── Router ───────────────────────────────────────────────────────────────── */

async function route() {
  const view = document.getElementById('view');
  const hash = (location.hash || '#/dashboard').replace(/^#\//, '');
  const [name, param] = hash.split('/');
  const key = param ? `${name}/:id` : name;
  const renderer = VIEWS[key] ?? VIEWS[name] ?? VIEWS.dashboard;

  closeDrawer();
  view.textContent = '';
  view.appendChild(el('p', { class: 'loading', text: 'loading…' }));
  setStatus(`loading ${name}…`);
  renderNav(await navCounts().catch(() => ({})));
  renderNav({}, document.getElementById('sheet-nav'));

  try {
    const content = await renderer(param ? { id: decodeURIComponent(param) } : {});
    view.textContent = '';
    for (const block of [].concat(content)) if (block) view.appendChild(block);
    setStatus(`${name} ready · ${MODE_COPY[dataMode.source]?.pill ?? ''}`);
  } catch (error) {
    view.textContent = '';
    view.appendChild(el('h1', { text: 'Could not load this view' }));
    view.appendChild(el('div', { class: 'error-box', text: error.message }));
    view.appendChild(el('p', { class: 'small muted', text: 'Start the engine with: genesis serve — then open this page again. Offline with no cache yet? The bundled snapshot will appear once you load any view with the server up once.' }));
    setStatus(`error: ${error.message}`);
  }
  window.scrollTo({ top: 0 });
}

async function navCounts() {
  const [stats, health] = await Promise.all([api('/api/stats'), api('/api/health').catch(() => null)]);
  const processing = stats.processing ?? {};
  const progressPill = document.getElementById('progress-pill');
  if (progressPill) progressPill.textContent = `${stats.state?.progress_percent ?? 0}% · ${stats.state?.current_phase ?? '—'}`;
  const eventsNode = document.getElementById('status-events');
  if (eventsNode) eventsNode.textContent = `events: ${processing.events ?? 0}`;
  const indexedNode = document.getElementById('status-indexed');
  if (indexedNode) indexedNode.textContent = `indexed: ${processing.indexed_entities ?? 0}`;
  const metaNode = document.getElementById('meta-node');
  if (metaNode && health) metaNode.textContent = `node ${health.node ?? '—'}`;
  const metaSqlite = document.getElementById('meta-sqlite');
  if (metaSqlite && health) metaSqlite.textContent = `sqlite ${health.sqlite ?? '—'}`;
  const metaDeps = document.getElementById('meta-deps');
  if (metaDeps && health) metaDeps.textContent = `${health.dependencies ?? 0} dependencies`;
  const metaOffline = document.getElementById('meta-offline');
  if (metaOffline && health) metaOffline.textContent = health.offline_capable ? 'offline ready' : 'offline unavailable';
  return {
    sessions: processing.sessions, decisions: processing.decisions, tasks: processing.tasks,
    requirements: processing.requirements, evolve: processing.lessons, knowledge: processing.indexed_entities,
    graph: processing.nodes, checkpoints: stats.state?.last_checkpoint ? 1 : 0,
  };
}

/* ── Arranque / Boot ──────────────────────────────────────────────────────── */

wireChrome();
window.addEventListener('hashchange', route);
window.addEventListener('DOMContentLoaded', async () => {
  await registerServiceWorker();
  await probe();
  await route();
});
if (document.readyState !== 'loading') {
  registerServiceWorker().then(probe).then(route);
}
